<?php
$lang = isset($_SESSION['SES_LANG']) ?  $_SESSION['SES_LANG'] : 'id';;

if ($lang == "en") {
    define("_WELCOME", "Welcome");
    define("_HOME", "Home");
    define("_SEARCH", "Search");
    define("_DASHBOARD", "Dashboard");
    define("_FAVOURITE", "Favourite");
    define("_PROFILE", "Profile");
    define("_USERPROFILE", "User Profile");
    define("_USERGUIDE", "User Guide");
    define("_HELP", "Help");
    define("_LANGUAGE", "Language");
    define("_LOGOUT", "Logout");
    define("_5LATESTSOP", "5 Latest SOP");
    define("_5LATESTIM", "5 Latest Internal Memo");
    define("_TITLE", "Title");
    define("_DATE", "Date");
    define("_DOCUMENT", "Document");
    define("_PAGE", "Page");
    define("_SEARCHRESULT", "Search Results of");
    define("_SELECT", "Select");
    define("_CATEGORY", "Category");
    define("_ALL", "All");
    define("_ACTIVITYREPORT", "User Activity Report");
    define("_5LASTREAD", "5 Last Read Documents");
    define("_5MOSTREAD", "5 Most Read Documents");
    define("_CODE", "Code");
    define("_ADDTOFAVOURITE", "Add to favourite");
    define("_DELETEFROMFAVOURITE", "Delete from favourite");
    define("_VIEWDOCUMENT", "View document detail");
    define("_DATE_SOP", "SK Date");
    define("_DATE_IM", "Memo Date");
    define("_DATE_READING", "Reading Date");
    define("_BACK", "Back");
    define("_POPULARBOOK", "Popular Book");
    define("_NEWBOOK", "New Book");
    define("_AUTHOR", "Author");
    define("_PUBLISHER", "Publisher");
    define("_LOCATION", "Location");
    define("_READ", "Read");
    define("_FILENAME", "File Name");
    define("_SIZE", "Size");
    define("_YEAR", "Year");
    define("_DESC", "Desc");
}

if ($lang == "id") {
    define("_WELCOME", "Selamat Datang");
    define("_HOME", "Beranda");
    define("_SEARCH", "Cari");
    define("_DASHBOARD", "Dashboard");
    define("_FAVOURITE", "Favorit");
    define("_PROFILE", "Profil");
    define("_USERPROFILE", "Profil Pengguna");
    define("_USERGUIDE", "Buku Petunjuk");
    define("_HELP", "Bantuan");
    define("_LANGUAGE", "Bahasa");
    define("_LOGOUT", "Keluar");
    define("_5LATESTSOP", "5 SOP Terbaru");
    define("_5LATESTIM", "5 Internal Memo Terbaru");
    define("_TITLE", "Judul");
    define("_DATE", "Tanggal");
    define("_DOCUMENT", "Dokumen");
    define("_PAGE", "Halaman");
    define("_SEARCHRESULT", "Hasil pencarian dari");
    define("_SELECT", "Pilih");
    define("_CATEGORY", "Kategori");
    define("_ALL", "Semua");
    define("_ACTIVITYREPORT", "Laporan Aktifitas Pengguna");
    define("_5LASTREAD", "5 Dokumen Terakhir Dibaca");
    define("_5MOSTREAD", "5 Dokumen Paling Sering Dibaca");
    define("_CODE", "Kode");
    define("_ADDTOFAVOURITE", "Tambah ke favorit");
    define("_DELETEFROMFAVOURITE", "Hapus dari favorit");
    define("_VIEWDOCUMENT", "Lihat detil dokumen");
    define("_DATE_SOP", "Tanggal SK");
    define("_DATE_IM", "Tanggal Memo");
    define("_DATE_READING", "Tanggal Baca");
    define("_BACK", "Kembali");
    define("_POPULARBOOK", "Buku Populer");
    define("_NEWBOOK", "Buku Baru");
    define("_AUTHOR", "Pengarang");
    define("_PUBLISHER", "Penerbit");
    define("_LOCATION", "Lokasi");
    define("_READ", "Baca");
    define("_FILENAME", "Nama File");
    define("_SIZE", "Ukuran");
    define("_YEAR", "Tahun");
    define("_DESC", "Deskripsi");
    // define("_AUTHOR", "Kembali");
}
